version: '3'
services:
  app:
    build: docker/php
    container_name: lara-hillel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: lara-hillel-nginx
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/lara.local.conf:/etc/nginx/conf.d/lara.local.conf
    depends_on:
      - app
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./docker/mysql/lara-hillel:/var/lib/mysql
    container_name: lara-hillel-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lara_db
      MYSQL_USER: lara_user
      MYSQL_PASSWORD: lara_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8012:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=hillel-pma.local
