version: '3'
services:
  app:
    build: docker/php
    container_name: hillel_app_new
    restart: unless-stopped
    volumes:
      - ./:/var/www
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: hillel_nginx_new
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/hillel.local.conf:/etc/nginx/conf.d/hillel.local.conf
      - ./docker/nginx/login.local.conf:/etc/nginx/conf.d/login.local.conf
    depends_on:
      - app
  db:
  #  image: mysql:8.0.23
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./docker/mysql/hillel:/var/lib/mysql
    container_name: hillel_mysql_new
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: hillel_db
      MYSQL_USER: hillel_user
      MYSQL_PASSWORD: hillel_pwd
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8012:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=hillel-pma.local
